=== FoxCutter/Cubit/Tools/Opcode Tables/Opcodes.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="OpcodeData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Opcode" type="opcodeType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>     
    </xs:complexType>
  </xs:element>


  <xs:complexType name="opcodeType">
    <xs:sequence>
      <xs:element name="Encoding" type="opcodeEncoding" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>

    <!--Uses an index prefix-->
    <xs:attribute name="Index" type="xs:boolean" use="optional" default="false" />

    <!--Prefix for the opcode value-->
    <xs:attribute name="Prefix" type="xs:hexBinary" use="optional" default="00" />

    <!--The base value for the opcode-->
    <xs:attribute name="Value" type="xs:hexBinary" use="required" />
    
    <!--The function this opcode provides-->
    <xs:attribute name="Function" type="xs:string" use="required"/>
  
    <!--The function group this opcode is in-->
    <xs:attribute name="Group" type="xs:string" use="required"/>

    <!--The length of this opcode when encoded-->
    <xs:attribute name="Length" type="xs:short" use="required"/>
  </xs:complexType>


  <xs:complexType name="opcodeEncoding">
    <xs:sequence>
      <!--Mnemonic for this opcode-->
      <xs:element name="Mnemonic" type="xs:string" minOccurs="1"/>
      <!--Arguments-->
      <xs:element name="Arguments" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Arg" type="argType" minOccurs="0" maxOccurs="3" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <!--If this is an officaly documented opcode-->
      <xs:element name="Status" type="statusEnum" minOccurs="0" maxOccurs="4" default="Documented" />
      <!--Cycles(T states) count for execution non-jmp, Cycles(T states) count for execution of jmp-->
      <xs:element name="Cycles" type="xs:string" minOccurs="1" maxOccurs="4"/>
      <!--Effected Flags-->
      <xs:element name="Flags" type="xs:string" minOccurs="0" maxOccurs="4"/>
      <!--Description of this opcode-->
      <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="4"/>
    </xs:sequence>

    <!--This is the preferred encoding for this opcode-->
    <xs:attribute name="Preferred" type="xs:boolean" use="optional" default="true"/>

    <!--The platform this encoding is for, seperated by a comma -->
    <xs:attribute name="Platform" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="argType">
    <xs:simpleContent>
      <!--The type of the argument-->
      <xs:extension base="argTypeEnum">
        <!--How this argument is encoded into the opcode-->
        <xs:attribute name="encoding" type="encodingEnum" use="optional" default="Implicit"/>
        <!--If true, the value is part of the encoded data, but not provided durring assambly-->
        <xs:attribute name="hidden" type="xs:boolean" use="optional" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="statusEnum">
    <xs:restriction base="xs:string">
      <!--An offical and documented opcode-->
      <xs:enumeration value="Documented"/>
      <!--An undocumented opcode, and can be assambled-->
      <xs:enumeration value="Undocumented"/>
      <!--An undocumented opcode, but can only be executed-->
      <xs:enumeration value="ExecuteOnly"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="encodingEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None"/>

      <!--Source Operand 0b00000111 0x07-->
      <xs:enumeration value="Source"/>

      <!--Destination Operand and Flag encodding 0b00111000 0x38-->
      <xs:enumeration value="Dest"/>
      <xs:enumeration value="Flag"/>

      <!--Word register 0b00110000 0x30-->
      <xs:enumeration value="WordReg"/>

      <!--Flag encoding, using only the top four flags 0b00011000 0x18-->
      <xs:enumeration value="HalfFlag"/>

      <!--Immidate data-->
      <xs:enumeration value="ByteImmidate"/>
      <xs:enumeration value="WordImmidate"/>

      <!--An index register (encoded via Implicit) with an offset encoding after the first byte of the opcode-->
      <xs:enumeration value="IndexOffset"/>

      <!--The argument is already endcoded into the value-->
      <xs:enumeration value="Implicit"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="argTypeEnum">
    <xs:restriction base="xs:string">

      <!--Any Byte Resiter (Not inculding M, I or R)-->
      <xs:enumeration value="ByteReg"/>
      
      <!--Specific Byte Registers-->
      <xs:enumeration value="ByteReg-B"/>
      <xs:enumeration value="ByteReg-C"/>
      <xs:enumeration value="ByteReg-D"/>
      <xs:enumeration value="ByteReg-E"/>
      <xs:enumeration value="ByteReg-H"/>
      <xs:enumeration value="ByteReg-L"/>
      <xs:enumeration value="ByteReg-M"/>
      <xs:enumeration value="ByteReg-A"/>

      <xs:enumeration value="ByteReg-I"/>
      <xs:enumeration value="ByteReg-R"/>

      <!--Byte Register used for addressing (C)-->
      <xs:enumeration value="ByteRegPtr-C"/>

      <!--Any word Register (BC, DE, HL or SP)-->
      <xs:enumeration value="WordReg"/>

      <!--Specific Word Registers-->
      <xs:enumeration value="WordReg-BC"/>
      <xs:enumeration value="WordReg-DE"/>
      <xs:enumeration value="WordReg-HL"/>
      <xs:enumeration value="WordReg-SP"/>
      <xs:enumeration value="WordReg-PSW"/>
      <xs:enumeration value="WordReg-AF"/>

      <!--AF'-->
      <xs:enumeration value="WordReg-AFAlt"/>

      <!--Word Registers BD or DE-->
      <xs:enumeration value="WordReg-BD"/>

      <!--SP+n-->
      <xs:enumeration value="WordReg-SP+Byte"/>

      <!--Word register used for addressing (rr)-->
      <xs:enumeration value="WordRegPtr-BC"/>
      <xs:enumeration value="WordRegPtr-DE"/>
      <xs:enumeration value="WordRegPtr-HL"/>
      <xs:enumeration value="WordRegPtr-SP"/>

      <!--Word Registers (BD) or (DE)-->
      <xs:enumeration value="WordRegPtr-BD"/>

      <!--(HLI) (HL+)-->
      <xs:enumeration value="WordRegPtr-HLI"/>
      <!--(HLD) (HL-)-->
      <xs:enumeration value="WordRegPtr-HLD"/>

      <!--IXL IHX IYL IYH -->
      <xs:enumeration value="ByteReg-Izb"/>
      
      <!--IX/IY-->
      <xs:enumeration value="WordReg-Iz"/>
      <!--(IX+n)/(IY+n)-->
      <xs:enumeration value="WordRegPtr-Iz"/>

      <!--00h 08h 10h 18h 20h 28h 30h 38h-->
      <xs:enumeration value="RstValue"/>
      <!--0 though 7-->
      <xs:enumeration value="Value"/>
      <!--Specific values-->
      <xs:enumeration value="Value-0"/>
      <xs:enumeration value="Value-1"/>
      <xs:enumeration value="Value-2"/>
      <xs:enumeration value="Value-8"/>

      <!--Immidate Data types-->
      <xs:enumeration value="Byte"/>
      <xs:enumeration value="Word"/>
      <xs:enumeration value="Address"/>
      <xs:enumeration value="Displacment"/>

      <!--Offset used for used for addressing (n)-->
      <xs:enumeration value="BytePtr"/>

      <!--Address (nn)-->
      <xs:enumeration value="AddressPtr"/>

      <!--($ff00 + n)-->
      <xs:enumeration value="HighMemPtr+Byte"/>
      <!--($ff00 + C)-->
      <xs:enumeration value="HighMemPtr+C"/>

      <!--Any flag-->
      <xs:enumeration value="Flag"/>
      
      <!--C & Z tests only-->
      <xs:enumeration value="HalfFlag"/>

      <!--Specific Flag-->
      <xs:enumeration value="Flag-NZ"/>
      <xs:enumeration value="Flag-Z"/>
      <xs:enumeration value="Flag-NC"/>
      <xs:enumeration value="Flag-CY"/>
      <xs:enumeration value="Flag-PO"/>
      <xs:enumeration value="Flag-PE"/>
      <xs:enumeration value="Flag-P"/>
      <xs:enumeration value="Flag-M"/>

      <xs:enumeration value="Flag-NK"/>
      <xs:enumeration value="Flag-K"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== FoxCutter/Cubit/Tools/Opcode Tables/z80 Opcodes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
-->

<OpcodeData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./Opcodes.xsd">
  <Opcode Value='00' Function='NOP' Group='General' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>NOP</Mnemonic>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>------</Flags>
      <Description>The CPU performs no operation during this machine cycle</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='01' Function='LOAD' Group='16-Bit Load' Length='3'>
    <Encoding Platform='z80'>
      <Mnemonic>LD</Mnemonic>
      <Arguments>
        <Arg encoding='WordReg'>WordReg</Arg>
        <Arg encoding='WordImmidate'>Word</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>2(10)</Cycles>
      <Flags>------</Flags>
      <Description>The 2-byte integer nn is loaded to the dd register pair</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='02' Function='LOAD' Group='8-Bit Load' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>LD</Mnemonic>
      <Arguments>
        <Arg encoding='WordReg'>WordRegPtr-BD</Arg>
        <Arg encoding='Direct'>ByteReg-A</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>2(7)</Cycles>
      <Flags>------</Flags>
      <Description>The contents of the Accumulator are loaded to the memory location specified by the contents of the register pair.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='03' Function='INC' Group='16-Bit Arithmetic' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>INC</Mnemonic>
      <Arguments>
        <Arg encoding='WordReg'>WordReg</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(6)</Cycles>
      <Flags>------</Flags>
      <Description>The contents of register pair ss (any of register pairs BC, DE, HL, or SP) are incremented.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='04' Function='INC' Group='8-Bit Arithmetic' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>INC</Mnemonic>
      <Arguments>
        <Arg encoding='Dest'>ByteReg</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>SZHP0-</Flags>
      <Description>Register r is incremented</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='05' Function='DEC' Group='8-Bit Arithmetic' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>DEC</Mnemonic>
      <Arguments>
        <Arg encoding='Dest'>ByteReg</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>SZHP1C</Flags>
      <Description>The byte specified by the m operand is decremented</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='06' Function='LOAD' Group='8-Bit Load' Length='2'>
    <Encoding Platform='z80'>
      <Mnemonic>LD</Mnemonic>
      <Arguments>
        <Arg encoding='Dest'>ByteReg</Arg>
        <Arg encoding='ByteImmidate'>Byte</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>2(7)</Cycles>
      <Flags>------</Flags>
      <Description>The 8-bit integer n is loaded to any register r.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='07' Function='RL' Group='Logical' Length='1'>
    <Encoding Preferred='true' Platform='z80'>
      <Mnemonic>RLCA</Mnemonic>
      <Arguments>
        <Arg encoding='Direct' hidden='true'>ByteReg-A</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>--0-0C</Flags>
      <Description>The contents of the Accumulator (register A) are rotated left 1-bit position. The sign bit (bit 7) is copied to the Carry flag and also to bit 0. Bit 0 is the least-significant bit.</Description>
    </Encoding>
    <Encoding Preferred='false' Platform='z80'>
      <Mnemonic>RLC</Mnemonic>
      <Arguments>
        <Arg encoding='Direct'>ByteReg-A</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>--0-0C</Flags>
      <Description>The contents of the Accumulator (register A) are rotated left 1-bit position. The sign bit (bit 7) is copied to the Carry flag and also to bit 0. Bit 0 is the least-significant bit.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='08' Function='EX' Group='16-Bit Load' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>EX</Mnemonic>
      <Arguments>
        <Arg encoding='Direct'>WordReg-AF</Arg>
        <Arg encoding='Direct'>WordReg-AFAlt</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>------</Flags>
      <Description>The 2-byte contents of the register pairs AF and AF' are exchanged.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='09' Function='ADD' Group='16-Bit Arithmetic' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>ADD</Mnemonic>
      <Arguments>
        <Arg encoding='Direct'>WordReg-HL</Arg>
        <Arg encoding='WordReg'>WordReg</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>3(11)</Cycles>
      <Flags>--H-0C</Flags>
      <Description>The contents of register pair ss (any of register pairs BC, DE, HL, or SP) are added to the contents of register pair HL and the result is stored in HL</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='0A' Function='LOAD' Group='8-Bit Load' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>LD</Mnemonic>
      <Arguments>
        <Arg encoding='Direct'>ByteReg-A</Arg>
        <Arg encoding='WordReg'>WordRegPtr-BD</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>2(7)</Cycles>
      <Flags>------</Flags>
      <Description>The contents of the memory location specified by the contents of the rr register pair are loaded to the Accumulator.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='0B' Function='DEC' Group='16-Bit Arithmetic' Length='1'>
    <Encoding Platform='z80'>
      <Mnemonic>DEC</Mnemonic>
      <Arguments>
        <Arg encoding='WordReg'>WordReg</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(6)</Cycles>
      <Flags>------</Flags>
      <Description>The contents of register pair ss (any of the register pairs BC, DE, HL, or SP) are decremented.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='0F' Function='RR' Group='Logical' Length='1'>
    <Encoding Preferred='true' Platform='z80'>
      <Mnemonic>RRCA</Mnemonic>
      <Arguments>
        <Arg encoding='Direct' hidden='true'>ByteReg-A</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>--0-0C</Flags>
      <Description>The contents of the Accumulator (register A) are rotated right 1-bit position. Bit 0 is copied to the Carry flag and also to bit 7. Bit 0 is the least- significant bit.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='0F' Function='RR-CY' Group='Logical' Length='1'>
    <Encoding Preferred='false' Platform='z80'>
      <Mnemonic>RRC</Mnemonic>
      <Arguments>
        <Arg encoding='Direct'>ByteReg-A</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>--0-0C</Flags>
      <Description>The contents of the Accumulator (register A) are rotated right 1-bit position. Bit 0 is copied to the Carry flag and also to bit 7. Bit 0 is the least- significant bit.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='10' Function='DJNZ' Group='Branch' Length='2'>
    <Encoding Platform='z80'>
      <Mnemonic>DJNZ</Mnemonic>
      <Arguments>
        <Arg encoding='ByteImmidate'>Displacment</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>3(13)</Cycles>
      <Flags>------</Flags>
      <Description>This instruction is similar to the conditional jump instructions except that a register value is used to determine branching. The B register is decremented, and if a non zero value remains, the value of the displacement e is added to the Program Counter (PC). The next instruction is fetched from the location designated by the new contents of the PC. The jump is measured from the address of the instruction Op Code and has a range of -126 to +129 bytes. The assembler automatically adjusts for the twice incremented PC.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='17' Function='RL-CY' Group='Logical' Length='1'>
    <Encoding Preferred='true' Platform='z80'>
      <Mnemonic>RLA</Mnemonic>
      <Arguments>
        <Arg encoding='Direct' hidden='true'>ByteReg-A</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>--0-0C</Flags>
      <Description>The contents of the Accumulator (register A) are rotated left 1-bit position through the Carry flag. The previous content of the Carry flag is copied to bit 0. Bit 0 is the least-significant bit.</Description>
    </Encoding>
    <Encoding Preferred='false' Platform='z80'>
      <Mnemonic>RL</Mnemonic>
      <Arguments>
        <Arg encoding='Direct'>ByteReg-A</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>1(4)</Cycles>
      <Flags>--0-0C</Flags>
      <Description>The contents of the Accumulator (register A) are rotated left 1-bit position through the Carry flag. The previous content of the Carry flag is copied to bit 0. Bit 0 is the least-significant bit.</Description>
    </Encoding>
  </Opcode>
  <Opcode Value='18' Function='JMPR' Group='Branch' Length='2'>
    <Encoding Platform='z80'>
      <Mnemonic>JR</Mnemonic>
      <Arguments>
        <Arg encoding='ByteImmidate'>Displacment</Arg>
      </Arguments>
      <Status>Documented</Status>
      <Cycles>3(12)</Cycles>
      <Flags>------</Flags>
