=== FoxCutter/Cubit/Tools-MU/z80-Opcodes.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="z80Opcodes">
    <xs:complexType>
      <xs:sequence minOccurs="1">
        <xs:element name="platform" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="opcode" type="opcodeType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string">
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="opcodeType">
    <xs:sequence>
      <xs:element name="mnemonic" type="xs:string"/>
      <xs:element name="args" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="arg" type="argType" minOccurs="0" maxOccurs="3"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="official" type="xs:string" minOccurs="0" />
      <xs:element name="function" type="xs:string"/>
      <xs:element name="cycles" type="xs:short" minOccurs="0" default="0" />
    </xs:sequence>
    <xs:attribute name="index" type="xs:boolean" use="optional" default="false"/>
    <xs:attribute name="prefix" type="xs:hexBinary" use="optional"/>
    <xs:attribute name="value" type="xs:hexBinary" use="required"/>
  </xs:complexType>

  <xs:complexType name="argType" >
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <!--<xs:attribute name="pos" type="xs:integer" use="required"/>-->
        <xs:attribute name="encoding" type="EncodingEnum" use="optional" default="None"/>
        <xs:attribute name="assumed" type="xs:boolean" use="optional" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:simpleType name="EncodingEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None"/>
      <!--0b00000111 0x07-->
      <xs:enumeration value="1"/>
      <!--0b00111000 0x38-->
      <xs:enumeration value="2"/>
      <!--0b00110000 0x30-->
      <xs:enumeration value="3"/>
      <!--0b00011000 0x18-->
      <xs:enumeration value="4"/>

      <xs:enumeration value="ByteImmidate"/>
      <xs:enumeration value="WordImmidate"/>
      <xs:enumeration value="IndexOffset"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== FoxCutter/Cubit/Tools-MU/Z80-Opcodes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    <opcode index='false' prefix='00' value='00'> 
      <mnemonic></mnemonic>
      <arg pos='0' assumed='true' encoding='0'></arg> See below
      <official></official>
      <function></function>
       
    </opcode>
      index - If this is used with the Index prefix (DD IX, FD IY)
      Prefix and value = Machinecode bytes    
      name - Opcode mnemonic
      Arg - see below
      official - Y = official, N = Undocumented (will execute), X = Undocumented, but can be used in assembly
      function - General function of this opoeration when executing 
      cycles - Machine cycle count
      
    <arg pos='0' assumed='true' encoding='0'>A</arg> 
      Pos - Which argument is it (0-2)
      assumed - If true the argument dosn't have to be provided during assembly, 
      Encoding - How the argument is encoded into the value of the machine code byte
      Value - How to argument is to be executed, not how it's assembled. Parsing rules are not provided in this file 
   
   Arguments:
     ByteReg-A, ByteReg-B, ByteReg-C, ByteReg-D, ByteReg-E, ByteReg-H, ByteReg-L - Byte Registers
     WordRegPtr-BC, WordRegPtr-DE, WordRegPtr-HL, WordRegPtr-SP - Indirect memory access
     WordReg-AFAlt - Alternate AF register
     WordReg-AF, WordReg-BC, WordReg-DE, WordReg-HL, WordReg-SP - Word Registers
     ByteReg-I, ByteReg-R - z80 special byte registers
     0, 1, 2 - None encoded numbers
     Byte, Word - Immidate data
     
   GameBoy Specific:
     HighMemPtr+C ($ff00 + C) - Indirect high memory access
     HighMemPtr+Byte, HighMemPtr ($ff00 + n) (n)  - Indirect high memory access
     WordRegPtr-HLD, WordRegPtr-HLI (HLD) (HLI) (HL+) (HL-) - Indirect memory access with increment/decrement
     WordReg-SP+Byte, SP + n - Indirect stack accress with offest
     
     WordReg/WordRegF:
        0 = BC         
        1 = DE         
        2 = HL         
        3 = SP/AF      

     ByteReg:
        0 = B
        1 = C
        2 = D
        3 = E
        4 = H
        5 = L
        6 = (HL)     
        7 = A

     ByteIndexReg:
        4 = IXH/IYH
        5 = IXL/IYH
      
     WordIndexReg:
        IX/IY

     WordIndexRegPtr:
        (IX + n)/(IY + n)
   
     Flag/HalfFlag:
        0 = FLAG-NZ         
        1 = FLAG-Z          
        2 = FLAG-NC         
        3 = FLAG-C
        4 = FLAG-PO         
        5 = FLAG-PE         
        6 = FLAG-P          
        7 = FLAG-M          
   
     Encoded
        0 - 7
        RST: 00, 08, 10, 18, 20, 28, 30, 38

     Disp:
        byte data, displacment from current location e-2
   
     Address:
        word data
   
     AddressPtr:
        (Address) - word data
   
   
   encodings
      1 = 00000111 0x07
      2 = 00111000 0x38
      3 = 00110000 0x30
      4 = 00011000 0x18
      WordImmidate = 2-byte following opcode
      ByteImmidate = 1-byte following opcode
      IndexOffset = 1-byte as part of the opcode


-->

<z80Opcodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./z80-Opcodes.xsd">
  <platform name="z80">

    <opcode value='00'>
      <mnemonic>NOP</mnemonic>
      <official>Y</official>
      <function>NOP</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='01'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg encoding='3'>WordReg</arg>
        <arg encoding='WordImmidate'>Word</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>10</cycles>
    </opcode>
    <opcode value='02'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg>WordRegPtr-BC</arg>
        <arg>ByteReg-A</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>7</cycles>
    </opcode>
    <opcode value='03'>
      <mnemonic>INC</mnemonic>
      <args>
        <arg encoding='3'>WordReg</arg>
      </args>
      <official>Y</official>
      <function>INC</function>
      <cycles>6</cycles>
    </opcode>
    <opcode value='04'>
      <mnemonic>INC</mnemonic>
      <args>
        <arg encoding='2'>ByteReg</arg>
      </args>
      <official>Y</official>
      <function>INC</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='05'>
      <mnemonic>DEC</mnemonic>
      <args>
        <arg encoding='2'>ByteReg</arg>
      </args>
      <official>Y</official>
      <function>DEC</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='06'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg encoding='2'>ByteReg</arg>
        <arg encoding='ByteImmidate'>Byte</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>7</cycles>
    </opcode>
    <opcode value='07'>
      <mnemonic>RLCA</mnemonic>
      <official>Y</official>
      <function>RL_A_CY</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='08'>
      <mnemonic>EX</mnemonic>
      <args>
        <arg>WordReg-AF</arg>
        <arg>WordReg-AFAlt</arg>
      </args>
      <official>Y</official>
      <function>EX</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='09'>
      <mnemonic>ADD</mnemonic>
      <args>
        <arg>WordReg-HL</arg>
        <arg encoding='3'>WordReg</arg>
      </args>
      <official>Y</official>
      <function>ADD</function>
      <cycles>11</cycles>
    </opcode>
    <opcode value='0A'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg>ByteReg-A</arg>
        <arg>WordRegPtr-BC</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>7</cycles>
    </opcode>
    <opcode value='0B'>
      <mnemonic>DEC</mnemonic>
      <args>
        <arg encoding='3'>WordReg</arg>
      </args>
      <official>Y</official>
      <function>DEC</function>
      <cycles>6</cycles>
    </opcode>
    <opcode value='0F'>
      <mnemonic>RRCA</mnemonic>
      <official>Y</official>
      <function>RR_A_CY</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='10'>
      <mnemonic>DJNZ</mnemonic>
      <args>
        <arg encoding='ByteImmidate'>Disp</arg>
      </args>
      <official>Y</official>
      <function>DJNZ</function>
      <cycles>13</cycles>
    </opcode>
    <opcode value='12'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg>WordRegPtr-DE</arg>
        <arg>ByteReg-A</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>7</cycles>
    </opcode>
    <opcode value='17'>
      <mnemonic>RLA</mnemonic>
      <official>Y</official>
      <function>RL_A</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='18'>
      <mnemonic>JR</mnemonic>
      <args>
        <arg encoding='ByteImmidate'>Disp</arg>
      </args>
      <official>Y</official>
      <function>JR</function>
      <cycles>12</cycles>
    </opcode>
    <opcode value='1A'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg>ByteReg-A</arg>
        <arg>WordRegPtr-DE</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>7</cycles>
    </opcode>
    <opcode value='1F'>
      <mnemonic>RRA</mnemonic>
      <official>Y</official>
      <function>RR_A</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='20'>
      <mnemonic>JR</mnemonic>
      <args>
        <arg encoding='4'>HalfFlag</arg>
        <arg encoding='ByteImmidate'>Disp</arg>
      </args>
      <official>Y</official>
      <function>JR</function>
      <cycles>12</cycles>
    </opcode>
    <opcode value='22'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg encoding='WordImmidate'>AddressPtr</arg>
        <arg>WordReg-HL</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>16</cycles>
    </opcode>
    <opcode value='27'>
      <mnemonic>DAA</mnemonic>
      <official>Y</official>
      <function>BCD_ADJUST</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='2A'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg>WordReg-HL</arg>
        <arg encoding='WordImmidate'>AddressPtr</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>16</cycles>
    </opcode>
    <opcode value='2F'>
      <mnemonic>CPL</mnemonic>
      <args>
        <arg>ByteReg-A</arg>
      </args>
      <official>Y</official>
      <function>NOT</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='32'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg encoding='WordImmidate'>AddressPtr</arg>
        <arg>ByteReg-A</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>13</cycles>
    </opcode>
    <opcode value='34'>
      <mnemonic>INC</mnemonic>
      <args>
        <arg>WordRegPtr-HL</arg>
      </args>
      <official>Y</official>
      <function>INC</function>
      <cycles>11</cycles>
    </opcode>
    <opcode value='35'>
      <mnemonic>DEC</mnemonic>
      <args>
        <arg>WordRegPtr-HL</arg>
      </args>
      <official>Y</official>
      <function>DEC</function>
      <cycles>11</cycles>
    </opcode>
    <opcode value='36'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg>WordRegPtr-HL</arg>
        <arg encoding='ByteImmidate'>Byte</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>10</cycles>
    </opcode>
    <opcode value='37'>
      <mnemonic>SCF</mnemonic>
      <official>Y</official>
      <function>CY_SET</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='3A'>
      <mnemonic>LD</mnemonic>
      <args>
        <arg>ByteReg-A</arg>
        <arg encoding='WordImmidate'>AddressPtr</arg>
      </args>
      <official>Y</official>
      <function>LD</function>
      <cycles>13</cycles>
    </opcode>
    <opcode value='3F'>
      <mnemonic>CCF</mnemonic>
      <official>Y</official>
      <function>CY_INVERT</function>
      <cycles>4</cycles>
    </opcode>
    <opcode value='40'>
      <mnemonic>LD</mnemonic>
